name: Build-Deploy-devnet
on:
  push:
    branches: [develop]

jobs:
  docker-build:
    # Name the Job
    name: Build
    runs-on: build
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to AWS ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: account-demo
          IMAGE_TAG: ${{github.sha}}
          REACT_APP_CLIENT_ID: FbqanG4CoL5TfFjfBxrJQgfDx2iA4BimsC4WcjRXurHD
          REACT_APP_REDIRECT_URI: https://account-demo.devnet.veladev.net
          REACT_APP_ACCOUNT_HOST: account.devnet.veladev.net
          REACT_APP_NETWORK_HOST: https://api.devnet.velas.com
          REACT_APP_SPONSOR_HOST: https://api-sponsor.devnet.velas.com
          REACT_APP_SPONSOR_PUB_KEY: EgJX7GpswpA8z3qRNuzNTgKKjPmw1UMfh5xQjFeVBqAK
          REACT_APP_HISTORY_HOST: https://api-history.devnet.velas.com
        run: |
          docker build --no-cache --build-arg REACT_APP_CLIENT_ID \
            --build-arg REACT_APP_CLIENT_ID \
            --build-arg REACT_APP_REDIRECT_URI \
            --build-arg REACT_APP_ACCOUNT_HOST \
            --build-arg REACT_APP_NETWORK_HOST \
            --build-arg REACT_APP_SPONSOR_HOST \
            --build-arg REACT_APP_SPONSOR_PUB_KEY \
            --build-arg REACT_APP_HISTORY_HOST \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=repository::$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"
  deploy:
    name: Deploy via Helmfile
    runs-on: deployer
    needs: docker-build
    steps:
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.6.0
        with:
          helmfile-version: "v0.131.0"
      - name: Check out velas-infra
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
      - name: Deploy via helmfile
        id: deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.docker-build.outputs.repository }}
          IMAGE_TAG: ${{ needs.docker-build.outputs.image_tag }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          mkdir -p ~/.kube && echo $KUBE_CONFIG_DATA|base64 --decode > ~/.kube/config
          helm plugin install https://github.com/databus23/helm-diff || true
          cd deploy
          helmfile -e prod-eu-monster1 -l namespace=devnet,name=velas-account-demo apply  --set image.tag=$IMAGE_TAG,image.repository=$ECR_REGISTRY/$ECR_REPOSITORY --skip-deps

