name: Build-Deploy-mainnet
on:
  push:
    branches: [master]

jobs:
  docker-build:
    name: Build and push
    runs-on: build
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_HOST }}
      - name: Build, tag, and push image 
        id: build
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}/velas
          REPOSITORY: account-demo
          IMAGE_TAG: ${{github.sha}}
          REACT_APP_CLIENT_ID: GbFVdaKFXRfpvBDTFHVChZ5umJpjYTvkXZ7oSZMNP8Lb
          REACT_APP_REDIRECT_URI: https://account-demo.velas.com
          REACT_APP_ACCOUNT_HOST: account.mainnet.velas.com
          REACT_APP_NETWORK_HOST: https://api.mainnet.velas.com
          REACT_APP_SPONSOR_HOST: https://api-sponsor.mainnet.velas.com
          REACT_APP_SPONSOR_PUB_KEY: EgJX7GpswpA8z3qRNuzNTgKKjPmw1UMfh5xQjFeVBqAK
          REACT_APP_HISTORY_HOST: https://api-history.velas.com
          REACT_APP_ACCOUNT_PROGRAM: VAcccHVjpknkW5N5R9sfRppQxYJrJYVV7QJGKchkQj5
        run: |
          docker build --no-cache --build-arg REACT_APP_CLIENT_ID \
            --build-arg REACT_APP_FAUCET \
            --build-arg REACT_APP_ACCOUNT_PROGRAM \
            --build-arg REACT_APP_CLIENT_ID \
            --build-arg REACT_APP_REDIRECT_URI \
            --build-arg REACT_APP_ACCOUNT_HOST \
            --build-arg REACT_APP_NETWORK_HOST \
            --build-arg REACT_APP_SPONSOR_HOST \
            --build-arg REACT_APP_SPONSOR_PUB_KEY \
            --build-arg REACT_APP_HISTORY_HOST \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  deploy:
    name: Deploy via Helmfile
    runs-on: deployer
    needs: docker-build
    container:
      image: quay.io/roboll/helmfile:v0.142.0
    steps:
      - name: Install ssh
        run: apk --update add openssh-client
      - name: Check out velas-infra
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ref: master
          ssh-key: ${{ secrets.SSH_KEY_INFRA }}
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA_LONDON_RAW }}
          context: "prod-london"
      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1.1.0
      - uses: adnsio/setup-age-action@v1.2.0
      - name: Deploy via helmfile
        id: deploy
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}/velas
          REPOSITORY: account-demo
          IMAGE_TAG: ${{github.sha}}
          SOPS_AGE_KEY: ${{ secrets.INFRA_AGE }}
        run: |
          helm plugin install https://github.com/jkroepke/helm-secrets --version v3.11.0 || true
          helm plugin install https://github.com/databus23/helm-diff || true
          cd deploy/prod-london
          helmfile -l namespace=mainnet,name=velas-account-demo apply  --set image.tag=$IMAGE_TAG,image.repository=$REGISTRY/$REPOSITORY --skip-deps
