name: Build-Deploy-testnet
on:
  push:
    branches: [testnet]

jobs:
  docker-build:
    # Name the Job
    name: Build
    runs-on: build
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to AWS ECR
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: account-demo
          IMAGE_TAG: ${{ github.sha }}
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID_TESTNET }}
          REACT_APP_ACCOUNT_CONRACT: ${{ secrets.REACT_APP_ACCOUNT_CONRACT_TESTNET }}
          REACT_APP_BACKEND_ACCOUNT: ${{ secrets.REACT_APP_BACKEND_ACCOUNT_TESTNET }}
          REACT_APP_AGENT_DOMAIN: account.testnet.velas.com
          REACT_APP_REDIRECT_URI: https://account-demo.testnet.velas.com
          REACT_APP_NODE_HOST: https://testnet.velas.com/rpc
          REACT_APP_EVM_HOST: https://explorer.testnet.velas.com/rpc/
        run: |
          docker build --no-cache --build-arg REACT_APP_CLIENT_ID \
            --build-arg REACT_APP_ACCOUNT_CONRACT \
            --build-arg REACT_APP_BACKEND_ACCOUNT \
            --build-arg REACT_APP_AGENT_DOMAIN \
            --build-arg REACT_APP_REDIRECT_URI \
            --build-arg REACT_APP_NODE_HOST \
            --build-arg REACT_APP_EVM_HOST \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=repository::$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"

  deploy:
    name: Deploy via Helmfile
    runs-on: deploy
    needs: docker-build
    steps:
      - name: Configure AWS credentials
        id: checkout
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.6.0
        with:
          helmfile-version: "v0.131.0"
      - name: Check out velas-infra
        uses: actions/checkout@master
        with:
          repository: velas/velas-infra
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
      - name: Deploy via helmfile
        id: deploy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ needs.docker-build.outputs.repository }}
          IMAGE_TAG: ${{ needs.docker-build.outputs.image_tag }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_AWS }}
        run: |
          mkdir -p ~/.kube && echo $KUBE_CONFIG_DATA|base64 --decode > ~/.kube/config
          cd deploy
          helmfile -e prod -l namespace=testnet,name=velas-account-demo apply  --set image.tag=$IMAGE_TAG,image.repository=$ECR_REGISTRY/$ECR_REPOSITORY --skip-deps
